name: Build Plugin ZIP

on:
    push:
        branches:
            - zip-action

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: zip-action

            - name: Install Composer dependencies
              run: composer install --no-dev

            - name: Install npm dependencies
              run: npm ci

            - name: Build plugin
              run: npm run build

            - name: Create plugin ZIP file
              run: npm run build-plugin

            - name: Create theme ZIP file
              run: npm run build-theme

            - name: Commit changes
              run: |
                  git config user.name github-actions[bot]
                  git config user.email 41898282+github-actions[bot]@users.noreply.github.com
                  git branch --show-current
                  git add .
                  git status
