name: Build Plugin ZIP

on:
    push:
        branches:
            - zip-action

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install Composer dependencies
              run: composer install --no-dev

            - name: Install npm dependencies
              run: npm ci

            - name: Build plugin
              run: npm run build

            - name: Create ZIP file
              uses: vimtor/action-zip@v1
              with:
                  files: build/ lib/ vendor/ wpmovies.php README.md
                  dest: wpmovies.zip
